### ISSUE TITLE
Problema ao integrar o framework via Carthage.

### ISSUE THREAD

**Issue by affbedran** [sambatech/player_sdk_ios#84] opened 2019-06-03 21:11 UTC
Ao executar o o comando `$carthage update`, a build falha, devido à versão do Swift depreciada (3.0). Estou usando Swift 5 em meu projeto.
Seguem os logs da build:

> /usr/bin/xcrun xcodebuild -project /Users/AndreBedran/Documents/01-WORK/AIS/imp-mobile-ios/Carthage/Checkouts/player_sdk_ios/SambaPlayer.xcodeproj -scheme SambaPlayer -configuration Release -derivedDataPath /Users/AndreBedran/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2.1_10E1001/player_sdk_ios/2.0.2 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/55/4b93ryn95j52d6pdxhvfdl540000gn/T/player_sdk_ios SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/AndreBedran/Documents/01-WORK/AIS/imp-mobile-ios/Carthage/Checkouts/player_sdk_ios)2019-06-03 18:00:41.403 xcodebuild[25307:1061891] [MT] PluginLoading: Required plug-in compatibility UUID 72F7D751-F810-43B8-A53F-1F1DFD74FC54 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SwiftLintXcode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2019-06-03 18:00:41.403 xcodebuild[25307:1061891] [MT] PluginLoading: Required plug-in compatibility UUID 72F7D751-F810-43B8-A53F-1F1DFD74FC54 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
User defaults from command line:
    IDEArchivePathOverride = /var/folders/55/4b93ryn95j52d6pdxhvfdl540000gn/T/player_sdk_ios
    IDEDerivedDataPathOverride = /Users/AndreBedran/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2.1_10E1001/player_sdk_ios/2.0.2

Build settings from command line:
    CARTHAGE = YES
    CLANG_ENABLE_CODE_COVERAGE = NO
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = iphoneos12.2
    SKIP_INSTALL = YES
    STRIP_INSTALLED_PRODUCT = NO

note: Using new build system
note: Planning build
note: Constructing build description
Build system information
error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'SambaPlayer')

Build system information
error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'SambaPlayer')

** ARCHIVE FAILED **

**Comment by dairan** [comment] 2019-06-05 16:23
[duplicado](https://github.com/sambatech/player_sdk_ios/issues/82)

**Comment by dairan** [comment] 2019-06-05 16:24
\
Duplicate of #82

**Comment by affbedran** [comment] 2019-06-10 13:59
Even though it's a duplicate, no actual solution was offered up to this date. The workaround mentioned in #82 is a bad practice and a short-term solution, and shows the lack of concern in updating this SDK.
I'm leaving this open, just in case someone actually cares about providing a decent solution for this critical issue.

**Comment by rangelvitor** [comment] 2019-07-03 17:29
Pessoal, vou fechar a issue pois atualizamos a o sdk e segue nova release com atualização do swift para versão 4.2: https://github.com/sambatech/player_sdk_ios/releases/tag/2.1.0

**Closed by rangelvitor** 2019-07-03 17:29 UTC
